/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData comedor1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mesa = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData armario = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData despacho = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData garaje = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sofa = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ventana = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData patio_delantero = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hierba = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sala_estar = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comedor = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bano = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sala_juegos = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData estudio = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casa = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData limpieza = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lavadora = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puerta = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ducha = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cama = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData terraza = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balcon = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData escalera = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jardin = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon__1_ = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cocina = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
